# Site
name: 'The A4E Journal'
description: "Discover The A4E Journal, your go-to source for in-depth insights, disability news, and best practices in accessibility. Our mission is to champion inclusivity, making 'Access for Everyone' more than just a name."
logo: 'assets/images/black-logo@2x.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'a4eorg'
email: 'info@a4e.org.in'
mailchimp-list: 'https://access.us6.list-manage.com/subscribe?u=12bdacef879da9fafa265ec19&id=09c5430fc7'

include: ["_pages"]
permalink: /:title

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    a4eorg:
      name:           A4Eorg
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg
      
    Akshit Anchan:
      name:           Akshit Anchan
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

     Tanvi Kalsi:
      name:           Tanvi Kalsi
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

     Alicia Prax:
      name:           Alicia Prax
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

     Manasa:
      name:           Manasa
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

     Surinder:
      name:           Surinder
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

    Malvika Baheti:
      name:           Malvika Baheti
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg

     Anushka:
      name:           Anushka
      site:           https://a4e.org.in
      avatar:         'assets/images/avatar-a4eorg.png'
      bio:            "Access for Everyone is a global initiative dedicated to creating a more accessible and inclusive society."
      email:          info@a4e.org.in
      twitter:        https://twitter.com/a4eorg
      
# Defaults
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: a4eorg
      avatar: /assets/images/avatar-a4eorg.png
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
